#pragma once

enum BrushType {
    BRUSH_FLATTEN = 0,
    BRUSH_SMOOTH,
    BRUSH_INFLATE,
    BRUSH_PINCH,
    BRUSH_CREASE,
    BRUSH_VTOOL,
    BRUSH_MOVE,
    BRUSH_DRAG,
    BRUSH_ELASTIC,
    // Group B
    BRUSH_MASK,
    BRUSH_PAINT,
    BRUSH_TWIST,
    BRUSH_LOCALSCALE,
    // Group C
    BRUSH_CLAY,
    BRUSH_CLAYBUILDUP,
    BRUSH_DAMSTANDARD,
    BRUSH_SQUAREBRUSH,
    BRUSH_VISIBILITY,
    BRUSH_MASK_GRADIENT_BLUR,
    BRUSH_MEASURE,
    BRUSH_DIVIDER,
    BRUSH_TRANSFORM,
    BRUSH_ARMATURE_SPHERES
};

enum class ModalMode {
    NONE = 0,
    RADIUS,
    INTENSITY,
    FOCAL_SHIFT,
    REMESH_RESOLUTION,
    TOPOLOGY_DETAIL,
    CAMERA_FOV
};

